version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: char_forge_backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
    environment:
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: char_forge_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/app/core/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: char_forge_frontend
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend

volumes:
  postgres_data:


